=== JustArion/keys/e1-player/src/data/keys.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "megacloud": {
      "type": "object",
      "properties": {
        "anime": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        },
        "movie": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        }
      },
      "required": [
        "anime",
        "movie"
      ]
    },
    "videostr": {
      "type": "object",
      "properties": {
        "anime": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        },
        "movie": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        }
      },
      "required": [
        "anime",
        "movie"
      ]
    },
    "cloudvidz": {
      "type": "object",
      "properties": {
        "anime": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        },
        "movie": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        }
      },
      "required": [
        "anime",
        "movie"
      ]
    },
    "cdnstreame": {
      "type": "object",
      "properties": {
        "anime": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        },
        "movie": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        }
      },
      "required": [
        "anime",
        "movie"
      ]
    },
    "streameeeeee": {
      "type": "object",
      "properties": {
        "anime": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        },
        "movie": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string",
              "minLength": 1
            },
            "hash": {
              "type": "string",
              "minLength": 1
            },
            "last_updated": {
              "type": "object",
              "properties": {
                "timestamp": {
                  "type": "number"
                },
                "time": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": [
                "timestamp",
                "time"
              ]
            }
          },
          "required": [
            "key",
            "hash",
            "last_updated"
          ]
        }
      },
      "required": [
        "anime",
        "movie"
      ]
    }
  },
  "required": [
    "megacloud",
    "videostr",
    "cloudvidz",
    "cdnstreame",
    "streameeeeee"
  ]
}

=== JustArion/keys/e1-player/src/data/keys.json
{
  "megacloud": {
    "anime": {
      "key": "7ee35e76838c6712a38bfe07bf44033763f55d970f61ae78726578ae48a1f325",
      "hash": "fd3207a",
      "last_updated": {
        "timestamp": 1752610484022,
        "time": "July 15, 2025 at 08:14 PM"
      }
    },
    "movie": {
      "key": "812dc850a908115d18f6487bbd3ca025004032caaccb861a85ecbdf069e6fcca",
      "hash": "3fbedde2",
      "last_updated": {
        "timestamp": 1752077619661,
        "time": "July 9, 2025 at 04:13 PM"
      }
    }
  },
  "videostr": {
    "anime": {
      "key": "7ee35e76838c6712a38bfe07bf44033763f55d970f61ae78726578ae48a1f325",
      "hash": "fd3207a",
      "last_updated": {
        "timestamp": 1752610484325,
        "time": "July 15, 2025 at 08:14 PM"
      }
    },
    "movie": {
      "key": "812dc850a908115d18f6487bbd3ca025004032caaccb861a85ecbdf069e6fcca",
      "hash": "3fbedde2",
      "last_updated": {
        "timestamp": 1752077619609,
        "time": "July 9, 2025 at 04:13 PM"
      }
    }
  },
  "cloudvidz": {
    "anime": {
      "key": "012XdynCdHxyO17drfSDjufyRLZRlgxYrQv0jYYISWsmTOBZALRKh3nY",
      "hash": "fb268040",
      "last_updated": {
        "timestamp": 1752596201496,
        "time": "July 15, 2025 at 04:16 PM"
      }
    },
    "movie": {
      "key": "hm0IIYodWBVN0se3p3OWGomd8KVP7rdfg6ZbA",
      "hash": "eec50ae8",
      "last_updated": {
        "timestamp": 1752067717957,
        "time": "July 9, 2025 at 01:28 PM"
      }
    }
  },
  "cdnstreame": {
    "anime": {
      "key": "012XdynCdHxyO17drfSDjufyRLZRlgxYrQv0jYYISWsmTOBZALRKh3nY",
      "hash": "fb268040",
      "last_updated": {
        "timestamp": 1752596201506,
        "time": "July 15, 2025 at 04:16 PM"
      }
    },
    "movie": {
      "key": "hm0IIYodWBVN0se3p3OWGomd8KVP7rdfg6ZbA",
      "hash": "eec50ae8",
      "last_updated": {
        "timestamp": 1752067717964,
        "time": "July 9, 2025 at 01:28 PM"
      }
    }
  },
  "streameeeeee": {
    "anime": {
      "key": "012XdynCdHxyO17drfSDjufyRLZRlgxYrQv0jYYISWsmTOBZALRKh3nY",
      "hash": "fb268040",
      "last_updated": {
        "timestamp": 1752596201146,
        "time": "July 15, 2025 at 04:16 PM"
      }
    },
    "movie": {
      "key": "hm0IIYodWBVN0se3p3OWGomd8KVP7rdfg6ZbA",
      "hash": "eec50ae8",
      "last_updated": {
        "timestamp": 1752067717671,
        "time": "July 9, 2025 at 01:28 PM"
      }
    }
  }
}
